### ISSUE TITLE
Warning: Undefined array key "complete form"

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/fivestar#20]
> Warning: Undefined array key "complete form" in fivestar_ajax_submit() (line 529 of /var/www/html/backdrop/modules/contrib/fivestar/fivestar.module).

Seeing this randomly (e.g. while viewing the `admin/modules` page).

**Comment by ProfessorGram** [comment]
Looks to me like:

1.  An array is being created
2.  A key in that array with the name "complete form" is being created
3.  The key is not being set to any value
4.  The code is then calling the fivestar_ajax_submit() function with an incomplete parameter

The fivestar_ajax_submit() function accepts two parameters:

function fivestar_ajax_submit($form, $form_state)

Unfortunately, the format of the incoming parameters are not implicitly specified as PHP is not strongly typed, NOR are they explicitly specified in the form of a function header comment.

The basic issue is that somewhere else in the code base is calling this function with a malformed parameter.

All PHP is doing here is saying where things finally broke down, not where the breakdown started.

Using grep, we get:

/sites/all/modules/fivestar $ grep -R "complete form" *
fivestar.module:  // Also need to pass on form_state and the complete form,
fivestar.module:  $new_element = fivestar_expand($form['vote'], $form_state, $form_state['complete form']);
includes/fivestar.theme.inc:  $form_state['complete form'] = array();

My inclination is to look at:

/sites/all/modules/fivestar/includes/fivestar.theme.inc

As you can see, the variable is initialized but not given a value:

includes/fivestar.theme.inc:  $form_state['complete form'] = array();

What's weird is the way that particular element is named.

Shouldn't it be "complete_form" a la:

includes/fivestar.theme.inc:  $form_state['complete_form'] = array();

Maybe there's a parsing issue because the variable name includes a space?

I would re-write the code to use a more compliant variable name format (complete_form) and do some testing

So, there are two problems that may be the root cause of the issue:

The line:
$form_state['complete form'] = array();

1) Contains a space in the variable, which is probably a no-no
Proposed solution:  replace space with underscore

2) Initializes the variable to NULL, which may also be a no-no
Proposed solution:  initialize variable to a SANE value and not NULL

BUT in the absence of being able to consistently replicate the issue (which I have never personally seen) , it would prove to be very difficult to prove the fixes I am suggesting are the actual solution.

g.
----

**Comment by albanycomputers** [comment]
Looking at the code...

"complete form" is only referenced at that location...  
fivestar.module lines 527 and 529

Where as "complete_form" is referenced...
fivestar.module lines 582, 605 & 606
includes\fivestar.theme.inc lines 26

but on the text it says 
```  // Also need to pass on form_state and the complete form,
  // just like form_builder() does.
  $new_element = fivestar_expand($form['vote'], $form_state, $form_state['complete form']);
```

Searching for form_bulider... i came across this...
https://api.drupal.org/api/drupal/includes%21form.inc/function/form_builder/7.x

```  // Allow for elements to expand to multiple elements, e.g., radios,
  // checkboxes and files.
  if (isset($element['#process']) && !$element['#processed']) {
    foreach ($element['#process'] as $process) {
      $element = $process($element, $form_state, $form_state['complete form']);
    }
    $element['#processed'] = TRUE;
  }
```
  
On a vanila BD site, the only other place ['complete form'] is referenced, that I can find is the color module...
color.module line 449

Where as ['complete_form']  is referenced quite a few more times...
batch.inc line 409
field.form.inc line 330
form.inc lines 1497, 1880, 1924, 4008 & 4026
system.admin.inc line 326
views_ui.admin.inc lines 699 & 735

So, I recon it's a typo... and should be ['complete_form']

**Comment by laryn** [comment]
Thanks @ProfessorGram and @albanycomputers -- while I do occasionally see an array key with a space (and I always do a double take, too), it does look like this one was inconsistent at some point in Drupal history ([e.g.](https://github.com/backdrop/backdrop/commit/ac7020aed30540f8522a1edacc3402886a517254)), and this is probably a vestige from those days. I'm going to agree with the assessment here and add the underscore.

**Comment by laryn** [comment]
@albanycomputers Care to file a core issue about the usage of `['complete form']` in color module?
